# Generated by Django 4.0.4 on 2022-07-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_shared_user_task_shares'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='task_shares',
            new_name='task_shared',
        ),
    ]
