# Generated by Django 4.0.4 on 2022-11-12 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_task_shares_task_shared'),
    ]

    operations = [
        migrations.CreateModel(
            name='time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summery_time', models.CharField(max_length=1000)),
                ('start_time', models.DateTimeField(verbose_name='date published')),
                ('end_time', models.DateTimeField(verbose_name='date published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='task_detail',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task_shared',
            name='task',
        ),
        migrations.DeleteModel(
            name='task',
        ),
        migrations.DeleteModel(
            name='task_detail',
        ),
        migrations.DeleteModel(
            name='task_shared',
        ),
    ]
