# Generated by Django 4.0.4 on 2022-11-12 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_time_table_remove_task_detail_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_table',
            old_name='summery_time',
            new_name='summery_event',
        ),
    ]
