# Generated by Django 4.0.4 on 2022-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_summery_time_time_table_summery_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
