# Generated by Django 4.0.4 on 2024-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='static/avatar/default.jpg', upload_to='static/avatar/'),
        ),
    ]
