# Generated by Django 4.0.4 on 2024-08-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_image_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='timeـspent',
            field=models.SmallIntegerField(null=True),
        ),
    ]
