# Generated by Django 4.0.4 on 2024-08-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_time_table_timeـspent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='timeـspent',
            field=models.TimeField(null=True),
        ),
    ]
