# Generated by Django 4.0.4 on 2024-08-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_time_table_timeـspent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_table',
            old_name='timeـspent',
            new_name='time_spent',
        ),
    ]
