# Generated by Django 4.0.4 on 2024-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_time_table_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_table',
            name='time_spent',
            field=models.FloatField(null=True),
        ),
    ]
