# Generated by Django 4.0.4 on 2024-08-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_time_table_time_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_table',
            name='seconds',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='time_spent',
            field=models.DateTimeField(null=True),
        ),
    ]
